### ISSUE TITLE
The #lstr reader macro is broken under cljs

### ISSUE THREAD

**Issue by ont-app** [ont-app/vocabulary#12]
Works in clj but not cljs..

Done when there are tests that call `#lstr "blah.en"` that work under `lein cljsbuild test`.

Work-around is to use (read-string "#lstr \"blah@en\"")

**Comment by ericdscott** [comment]
core_test/issue-12-language-tagged-strings-in-cljs has been defined, but does not yet pass when the "#lstr" tag is embedded directly in compiled code.
