### ISSUE TITLE
Validity of full URI keywords

### ISSUE THREAD

**Issue by bartkl** [ont-app/vocabulary#20]
Hello,

Many of us use the clj-kondo linter, and it doesn't agree with the generated keywords for non-prefixed URIs:

```Invalid keyword: https://w3id.org/schematransform/ExampleShape#BShape.      clj-kondo(syntax)```

It's a rather big inconvienice that clj-kondo marks this as a problem, since it makes autoformatting not work in that file.

When I read the Clojure Reader documentation, it is clear that `:` is not a valid symbol character, and neither does `/` seem to be (although it's slightly ambiguous).

I did notice this line in the README though:

> Characters which would choke the reader will be %-escaped. These characters differ depending on whether we're using the jvm or cljs platforms.

I'm not sure I follow this. Could you elaborate?

Thanks

**Comment by ericdscott** [comment]
Sorry that ont-app/vocabulary does not spark joy!

This file: https://github.com/ont-app/vocabulary/blob/master/src/ont_app/vocabulary/format.cljc has a function called 'get-escapes', which literally tests every UTF-8 codepoint inserted into a keyword at compile time and schedules it for escaping if an error is thrown.

There's similar logic to test for legal characters in a URI.

IIRC, there are some characters that are special cases when they come at the end.

I'm not entirely sure, but it may be possible to rebind the set of escaped characters to keep Ms. Kondo happy. 

I'm a bit slammed at work, but I'll try to take a look this weekend.  I also happily accept PRs!  :-)

Thanks for logging the issue!

**Comment by bartkl** [comment]
Hi Eric,

Oh no, it still definitely sparks joy :). In fact, I think my usage of the library was the problem. I manually created (for testing purposes) a keyword of the form `:http://www.example.com/something`, which made clj-kondo complain. I replaced this with `(keyword-for "http://www.example.com/something")` and all is well again.

If `keyword-for` and `uri-for` do the escaping underwater as you say, there's no problem as far as I'm concerned. At least, for now. I am curious what you think of this possible future scenario:

As I said, the [Reader documentation](https://clojure.org/reference/reader) disallows `:` and perhaps subsequent `/` chars, even though in reality Clojure is (currently) fine with it. @borkdude (clj-kondo maintainer) demonstrated to me that not all Clojure interpreters accept these keywords, and who knows at some point in the future the Clojure reader won't too anymore. This would cause the escapes to trigger for `:` and `/`, rendering the URI keyword much less readable. Arguably, this would remove the appeal for this solution. Do you have any thoughts on that? Of course this is in the future and might not become relevant, but I'm just curious.

Thanks!

**Comment by ont-app** [comment]
Are you speaking of babashka's clojure interpreter?

**Comment by borkdude** [comment]
@ont-app I showed him that CLJS (not an interpreter) does not accept this:

Try this in a CLJS REPL:

```
cljs.user=> 'http://foo
Syntax error reading source at (<cljs repl>:1).
Invalid symbol: http://foo.
```

```
cljs.user=> :http://foo
Syntax error reading source at (<cljs repl>:1).
Invalid keyword: :http://foo.
```

In general, the reader spec does not allow for more than one slash in a symbol or keyword, so even though existing readers accept it, it is documented as unsupported.
